### ISSUE TITLE
isShimmering not stop

### ISSUE THREAD

**Issue by wildercs** [BeauNouvelle/ShimmerView-Swift#2]
when you tried to disable the isShimmering = false option, it does not work.
The problem is this line: https://github.com/BeauNouvelle/ShimmerSwift/blob/e114f9a488f6acc4e0ed8e043b397390cdfec932/Shimmer/ShimmeringLayer.swift#L199

The Solution is: 
` guard let maskLayer = maskLayer else { return }`

**Comment by BeauNouvelle** [comment]
All fixed. thank you
