### ISSUE TITLE
Why library requires iOS 9.0+ but found iOS 10.0 in pod file

### ISSUE THREAD

**Issue by huuchi207** [BeauNouvelle/ShimmerView-Swift#9]
In READ.ME, you mention:
```
Requirement:
iOS 9.0+
```

but I found in Podfile, i found:
`platform :ios, '10.0'`

Please back to iOS 9 in Podfile. Your library helps me a lot.
Thank you so much

**Comment by BeauNouvelle** [comment]
sorry if this is too late. I've made that change
